Import libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

Load Dataset

In [2]:
df = pd.read_csv(
    "../raw_data/customer_support_tickets.csv"
)

df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

Check dataset size

In [3]:
df.shape

(8469, 17)

Check column names

In [4]:
df.columns.tolist()

['Ticket ID',
 'Customer Name',
 'Customer Email',
 'Customer Age',
 'Customer Gender',
 'Product Purchased',
 'Date of Purchase',
 'Ticket Type',
 'Ticket Subject',
 'Ticket Description',
 'Ticket Status',
 'Resolution',
 'Ticket Priority',
 'Ticket Channel',
 'First Response Time',
 'Time to Resolution',
 'Customer Satisfaction Rating']

Check data types

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   str
 2   Customer Email                8469 non-null   str
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   str
 5   Product Purchased             8469 non-null   str
 6   Date of Purchase              8469 non-null   str
 7   Ticket Type                   8469 non-null   str
 8   Ticket Subject                8469 non-null   str
 9   Ticket Description            8469 non-null   str
 10  Ticket Status                 8469 non-null   str
 11  Resolution                    2769 non-null   str
 12  Ticket Priority               8469 non-null   str
 13  Ticket Channel                8469 non-null   str
 14  First Response Time           5650 non-null   str
 15  Time to Resolution            2769 non-null   str
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), str(14)
memory usage: 1.1 MB

Check for missing values

In [8]:
missing_values = (
    df.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing_values

Customer Satisfaction Rating    5700
Resolution                      5700
Time to Resolution              5700
First Response Time             2819
Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Ticket Subject                     0
Ticket Type                        0
Date of Purchase                   0
Product Purchased                  0
Ticket Priority                    0
Ticket Status                      0
Ticket Description                 0
Ticket Channel                     0
dtype: int64

Check for duplicate records

In [6]:
df.duplicated().sum()

np.int64(0)

Basic statistics

In [7]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Ticket ID,8469.0,NaN,NaN,NaN,4235.0,2444.934048,1.0,2118.0,4235.0,6352.0,8469.0
Customer Name,8469,8028,Michael Garcia,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Email,8469,8320,asmith@example.com,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Age,8469.0,NaN,NaN,NaN,44.026804,15.296112,18.0,31.0,44.0,57.0,70.0
Customer Gender,8469,3,Male,2896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Purchased,8469,42,Canon EOS,240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date of Purchase,8469,730,2020-10-21,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ticket Type,8469,5,Refund request,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ticket Subject,8469,16,Refund request,576,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ticket Description,8469,8077,I'm having an issue with the {product_purchase...,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ticket Status,8469,3,Pending Customer Response,2881,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Resolution,2769,2769,Case maybe show recently my computer follow.,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ticket Priority,8469,4,Medium,2192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ticket Channel,8469,4,Email,2143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
First Response Time,5650,5470,2023-06-01 01:21:19,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time to Resolution,2769,2728,2023-06-01 17:14:42,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Satisfaction Rating,2769.0,NaN,NaN,NaN,2.991333,1.407016,1.0,2.0,3.0,4.0,5.0

In [9]:
for col in [
    "Ticket Type",
    "Ticket Status",
    "Ticket Priority",
    "Ticket Channel"
]:
    print("\n", col)
    print(df[col].value_counts())

 Ticket Type
Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

 Ticket Status
Ticket Status
Pending Customer Response    2881
Open                         2819
Closed                       2769
Name: count, dtype: int64

 Ticket Priority
Ticket Priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64

 Ticket Channel
Ticket Channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64

In [10]:
id="v5n2v1"
df["Product Purchased"].value_counts()

Product Purchased
Canon EOS                         240
GoPro Hero                        228
Nest Thermostat                   225
Philips Hue Lights                221
Amazon Echo                       221
LG Smart TV                       219
Sony Xperia                       217
Roomba Robot Vacuum               216
LG OLED                           213
Apple AirPods                     213
iPhone                            212
Sony 4K HDR TV                    210
LG Washing Machine                208
Garmin Forerunner                 208
Canon DSLR Camera                 206
Nikon D                           204
Nintendo Switch Pro Controller    203
Google Pixel                      203
Sony PlayStation                  202
Fitbit Charge                     202
Microsoft Office                  200
HP Pavilion                       200
Dyson Vacuum Cleaner              198
Amazon Kindle                     198
Google Nest                       198
Bose SoundLink Speaker            197
Autodesk AutoCAD                  196
Microsoft Xbox Controller         196
Samsung Galaxy                    194
PlayStation                       192
Fitbit Versa Smartwatch           191
Microsoft Surface                 190
Bose QuietComfort                 190
Samsung Soundbar                  188
Xbox                              187
Asus ROG                          187
MacBook Pro                       186
Dell XPS                          185
GoPro Action Camera               183
Lenovo ThinkPad                   183
Adobe Photoshop                   181
Nintendo Switch                   178
Name: count, dtype: int64

In [11]:
df["Customer Satisfaction Rating"].value_counts()

Customer Satisfaction Rating
3.0    580
1.0    553
2.0    549
5.0    544
4.0    543
Name: count, dtype: int64

In [ ]:
df["Product Purchased"].nunique()

42

:

In [13]:
df["Product Purchased"].value_counts()

Product Purchased
Canon EOS                         240
GoPro Hero                        228
Nest Thermostat                   225
Philips Hue Lights                221
Amazon Echo                       221
LG Smart TV                       219
Sony Xperia                       217
Roomba Robot Vacuum               216
LG OLED                           213
Apple AirPods                     213
iPhone                            212
Sony 4K HDR TV                    210
LG Washing Machine                208
Garmin Forerunner                 208
Canon DSLR Camera                 206
Nikon D                           204
Nintendo Switch Pro Controller    203
Google Pixel                      203
Sony PlayStation                  202
Fitbit Charge                     202
Microsoft Office                  200
HP Pavilion                       200
Dyson Vacuum Cleaner              198
Amazon Kindle                     198
Google Nest                       198
Bose SoundLink Speaker            197
Autodesk AutoCAD                  196
Microsoft Xbox Controller         196
Samsung Galaxy                    194
PlayStation                       192
Fitbit Versa Smartwatch           191
Microsoft Surface                 190
Bose QuietComfort                 190
Samsung Soundbar                  188
Xbox                              187
Asus ROG                          187
MacBook Pro                       186
Dell XPS                          185
GoPro Action Camera               183
Lenovo ThinkPad                   183
Adobe Photoshop                   181
Nintendo Switch                   178
Name: count, dtype: int64